GET http://localhost:3000/books/

###

POST http://localhost:3000/books/
Content-Type: application/json

{
        "bookId": 60,
        "title": "The Watcher",
        "author": "Dean Koontz",
        "genre": "Thriller",
        "pages": "470",
        "publishedDate": "1995-06-17"
}


###

PUT http://localhost:3000/books/60/
Content-Type: application/json

{
        "title": "The Watcher",
        "author": "Dean Koontz",
        "genre": "Thriller",
        "pages": "490",
        "publishedDate": "1995-06-17"
}

###

DELETE http://localhost:3000/books/11/


###

GET http://localhost:3000/books/11/

